name: "Verus Coin Miner"
description: "Mine Verus Coin in Home Assistant"
version: "1.0.0"
slug: "verus-coin-miner"
init: false
arch:
  - aarch64
  - amd64
  - armv7
url: "https://github.com/filippoberti2020/VerusCoinMiner-HomeAssistantAddon"
apparmor: true
backup: hot
tmpfs: true
stage: alpha

options:
  wallet_address: "your_wallet_address"
  mining_pool: "your_mining_pool"
  usernames: "miner_name"
  verus_password: ""
schema:
  wallet_address: str
  mining_pool: str

